CREATE TABLE "workspaces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar
);
--> statement-breakpoint
DROP INDEX "slug_idx";--> statement-breakpoint
DROP INDEX "title_idx";--> statement-breakpoint
DROP INDEX "email_idx";--> statement-breakpoint
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "slug_idx" ON "posts" USING btree ("slug" text_ops);--> statement-breakpoint
CREATE INDEX "title_idx" ON "posts" USING btree ("title" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "email_idx" ON "users" USING btree ("email" text_ops);